[build]
  command = "bun run build"
  publish = "dist"

[dev]
  framework = "#custom"
  command = "bun run vite"
  targetPort = 7412
  port = 5173
  publish = "dist"

[functions]
  directory = "api"

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


